<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyTauHoa" Class="QuanLyDuongSatDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-H5BQAG2\SQLEXPRESS;Initial Catalog=QuanLyTauHoa;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QuanLyTauHoaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Chuyen" Member="Chuyens">
    <Type Name="Chuyen">
      <Column Name="MaChuyen" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaTuyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GioKhoiHanh" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Association Name="Chuyen_ChuyenTau" Member="ChuyenTaus" ThisKey="MaChuyen" OtherKey="MaChuyen" Type="ChuyenTau" />
      <Association Name="Tuyen_Chuyen" Member="Tuyen" ThisKey="MaTuyen" OtherKey="MaTuyen" Type="Tuyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ve" Member="Ves">
    <Type Name="Ve">
      <Column Name="SoVe" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDatVe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaLoaiVe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrangThaiVe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayBanVe" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaGhe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaKhach" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhiTraVe" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Ghe_Ve" Member="Ghe" ThisKey="MaGhe" OtherKey="MaGhe" Type="Ghe" IsForeignKey="true" />
      <Association Name="KhachHang_Ve" Member="KhachHang" ThisKey="MaKhach" OtherKey="MaKhach" Type="KhachHang" IsForeignKey="true" />
      <Association Name="LoaiVe_Ve" Member="LoaiVe" ThisKey="MaLoaiVe" OtherKey="MaLoaiVe" Type="LoaiVe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChuyenTau" Member="ChuyenTaus">
    <Type Name="ChuyenTau">
      <Column Name="MaChuyenTau" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaChuyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTau" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayKhoiHanh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedByUser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedByUser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateUpdated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ChuyenTau_LoaiVe" Member="LoaiVes" ThisKey="MaChuyenTau" OtherKey="MaChuyenTau" Type="LoaiVe" />
      <Association Name="Chuyen_ChuyenTau" Member="Chuyen" ThisKey="MaChuyen" OtherKey="MaChuyen" Type="Chuyen" IsForeignKey="true" />
      <Association Name="Tau_ChuyenTau" Member="Tau" ThisKey="MaTau" OtherKey="MaTau" Type="Tau" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ga" Member="Gas">
    <Type Name="Ga">
      <Column Name="MaGa" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenGa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaThanhPhoTinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Ga_Tuyen" Member="Tuyens" ThisKey="MaGa" OtherKey="GaDi" Type="Tuyen" />
      <Association Name="Ga_Tuyen1" Member="Tuyens1" ThisKey="MaGa" OtherKey="GaDen" Type="Tuyen" />
      <Association Name="ThanhPho_Tinh_Ga" Member="ThanhPho_Tinh" ThisKey="MaThanhPhoTinh" OtherKey="MaThanhPhoTinh" Type="ThanhPho_Tinh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ghe" Member="Ghes">
    <Type Name="Ghe">
      <Column Name="MaGhe" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenGhe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DaXoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MaToa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Ghe_Ve" Member="Ves" ThisKey="MaGhe" OtherKey="MaGhe" Type="Ve" />
      <Association Name="Toa_Ghe" Member="Toa" ThisKey="MaToa" OtherKey="MaToa" Type="Toa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKhach" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="SoDT" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="KhachHang_Ve" Member="Ves" ThisKey="MaKhach" OtherKey="MaKhach" Type="Ve" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiVe" Member="LoaiVes">
    <Type Name="LoaiVe">
      <Column Name="MaLoaiVe" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaChuyenTau" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaVe" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LoaiVe" Member="LoaiVe1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LoaiVe_Ve" Member="Ves" ThisKey="MaLoaiVe" OtherKey="MaLoaiVe" Type="Ve" />
      <Association Name="ChuyenTau_LoaiVe" Member="ChuyenTau" ThisKey="MaChuyenTau" OtherKey="MaChuyenTau" Type="ChuyenTau" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NganHang" Member="NganHangs">
    <Type Name="NganHang">
      <Column Name="MaNganHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SoDu" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="CMND" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MaBaoMat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuanTri" Member="QuanTris">
    <Type Name="QuanTri">
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tau" Member="Taus">
    <Type Name="Tau">
      <Column Name="MaTau" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Tau_ChuyenTau" Member="ChuyenTaus" ThisKey="MaTau" OtherKey="MaTau" Type="ChuyenTau" />
      <Association Name="Tau_Toa" Member="Toas" ThisKey="MaTau" OtherKey="MaTau" Type="Toa" />
    </Type>
  </Table>
  <Table Name="dbo.ThanhPho_Tinh" Member="ThanhPho_Tinhs">
    <Type Name="ThanhPho_Tinh">
      <Column Name="MaThanhPhoTinh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenThanhPhoTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ThanhPho_Tinh_Ga" Member="Gas" ThisKey="MaThanhPhoTinh" OtherKey="MaThanhPhoTinh" Type="Ga" />
    </Type>
  </Table>
  <Table Name="dbo.Toa" Member="Toas">
    <Type Name="Toa">
      <Column Name="MaToa" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaTau" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LoaiCho" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenToa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Toa_Ghe" Member="Ghes" ThisKey="MaToa" OtherKey="MaToa" Type="Ghe" />
      <Association Name="Tau_Toa" Member="Tau" ThisKey="MaTau" OtherKey="MaTau" Type="Tau" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tuyen" Member="Tuyens">
    <Type Name="Tuyen">
      <Column Name="MaTuyen" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GaDi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GaDen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TuyenCha" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateUpdated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedByUser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedByUser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Tuyen_Chuyen" Member="Chuyens" ThisKey="MaTuyen" OtherKey="MaTuyen" Type="Chuyen" />
      <Association Name="Tuyen_Tuyen" Member="Tuyens" ThisKey="MaTuyen" OtherKey="TuyenCha" Type="Tuyen" />
      <Association Name="Ga_Tuyen" Member="Ga" ThisKey="GaDi" OtherKey="MaGa" Type="Ga" IsForeignKey="true" />
      <Association Name="Ga_Tuyen1" Member="Ga1" ThisKey="GaDen" OtherKey="MaGa" Type="Ga" IsForeignKey="true" />
      <Association Name="Tuyen_Tuyen" Member="Tuyen1" ThisKey="TuyenCha" OtherKey="MaTuyen" Type="Tuyen" IsForeignKey="true" />
    </Type>
  </Table>
</Database>